### PR TITLE
eliminates passive voice in its majority

### PR DESCRIPTION
**Pull request by cal27279**
Hi! @catlook Would you please review & edit this when you have a chance? Thank you!

### CODE REVIEW

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree.

**Review by cal27279 — COMMENTED** [review]
I agree! Thank you!

**Review by robb-romans — CHANGES_REQUESTED** [review]
Due to changes to enable search, please rebase and push. Thank you.

**Comment by cal27279** [comment]
rebasing unsuccessful

**Pull request closed without merging**
