### PR TITLE
Add blog: Four AWS multi-region architecture considerations

### PR DESCRIPTION
**Pull request by cal27279**
Hi @catlook Would you please review and edit this when you get a chance? Thank you!!!

### CODE REVIEW

**Comment by catlook** [comment]
first thing tomorrow!

**Comment by cal27279** [comment]
> first thing tomorrow!

Of course @catlook !

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree.  Remember if a company or product needs a trademark, you only do it once-the first time it appears in the doc!

**Comment by cal27279** [comment]
> @cal27279 review my edits and see if you agree. Remember if a company or product needs a trademark, you only do it once-the first time it appears in the doc!

Thank you @catlook I'll remember that. =)

**Review by viridaria — APPROVED** [review]

**Pull request merged**
