### PR TITLE
Add Vale linting CI

### PR DESCRIPTION
**Pull request by robb-romans**

### CODE REVIEW

**Comment by robb-romans** [comment]
image

**Comment by robb-romans** [comment]
If a PR is opened here from a branch on a forked repo, the Vale CI checks run *on the fork*. 
image

Vale annotations into a main repo PR from a fork are not yet supported. See limitations here: https://github.com/errata-ai/vale-action#limitations.

Any errors or warnings in Vale will show as a failed check. The output from Vale can help with awareness of needed edits to grammar, spelling, or style. The human reviewing and merging the PR must decide if the failures can be ignored or should be fixed.

**Comment by robb-romans** [comment]
For information about the accept and reject vocabulary files, see https://docs.errata.ai/vale/vocab
These are case sensitive.

**Comment by robb-romans** [comment]
If this shows up in the GitHub required checks section after merging, I'll remove it from required (making it non-blocking) in the repo settings.

**Review by codebyravi — APPROVED** [review]

**Pull request merged**
