### PR TITLE
Add blog: Whitepaper: Automating Windows Workloads on AWS

### PR DESCRIPTION
**Pull request by cal27279**
Hi @stephamon could you please review and edit this when you have a chance? Thank you

### CODE REVIEW

**Comment by catlook** [comment]
@cal27279 Neither white paper nor slides are available. I agree that we should not publish or migrate this post. Just close it and move on.  Sorry I didn't catch that when I marked posts to migrate!

**Review by catlook — CHANGES_REQUESTED** [review]
Do not publish.  Downloads are AWOL

**Comment by catlook** [comment]
@cal27279 where are we at on this?  Update the date when ready. to publish.

**Comment by cal27279** [comment]
I agree that we should not publish or migrate this post. Moving on.

**Pull request closed without merging**
