### PR TITLE
This blog discusses cloning an Oracle database using DBCA

### PR DESCRIPTION
**Pull request by bhaskarboserackspace**

### CODE REVIEW

**Review by bhaskarboserackspace — COMMENTED** [review]
author name edited

**Review by bhaskarboserackspace — COMMENTED** [review]
formatting tweaks

**Review by bhaskarboserackspace — COMMENTED** [review]
gravatar fix

**Comment by grizzlydev** [comment]
hey @bhaskarboserackspace this is in the root 2021 folder again - make sure you create a new folder for each blog post.

**Review by bhaskarboserackspace — COMMENTED** [review]
added gravatar email hash

**Review by bhaskarboserackspace — COMMENTED** [review]
added gravatar email hash

**Review by bhaskarboserackspace — COMMENTED** [review]
gravatar syntax correction

**Pull request merged**
