### PR TITLE
Amazon sagemaker studio

### PR DESCRIPTION
**Pull request by cal27279**
Testing build

### CODE REVIEW

**Comment by cal27279** [comment]
Hi @catlook would you please review & edit this when you have a chance? Thank you! Have a great week!

**Comment by cal27279** [comment]
This doesn't wanna build, right? @catlook

**Comment by catlook** [comment]
@cal27279 review my edits and see if you agree. If the author is an active Racker, please ask them to review this, just in case.

**Review by cal27279 — COMMENTED** [review]
I agree! Thank you!

**Review by Sterling463 — APPROVED** [review]

**Pull request merged**
