### PR TITLE
This blog explores Oracle Database migrations

### PR DESCRIPTION
**Pull request by bhaskarboserackspace**

### CODE REVIEW

**Comment by grizzlydev** [comment]
Hey @bhaskarboserackspace, two big issues stand out immediately, please correct these and ping me again and we can take another 

* The PR should have a descriptive title - `Add files via upload` is not - look at the [PR history], (https://github.com/rackerlabs/technical-blog/pulls?q=is%3Apr+is%3Aclosed) for examples, e.g. `Created blog post around AWS systems manager for instance patching`

* You've created all the content for this one blog post in main folder for 2021 `content/blog/2021/` - look at all the other blog posts, they are in their own folders for example `content/blog/2021/2021-08-27-aws-systems-manager-for-instance-patching`

**Comment by bhaskarboserackspace** [comment]
This blog explores Oracle Database Migrations

**Comment by bhaskarboserackspace** [comment]
@grizzlydev please consider this PR for merge. Thanks!

**Review by grizzlydev — APPROVED** [review]
LGTM @bhaskarboserackspace great work!

**Pull request merged**
