### PR TITLE
updates software versions

### PR DESCRIPTION
**Pull request by cal27279**
Hi @catlook could you please review:edit this when you have a chance? I'd appreciate it. Thanks!

### CODE REVIEW

**Comment by catlook** [comment]
@cal27279 You called for an edit, but the text of the article is just the template with no new content.  Ping me again when it's ready.

**Comment by cal27279** [comment]
> @cal27279 You called for an edit, but the text of the article is just the template with no new content. Ping me again when it's ready.

Apologies, @catlook  my bad. Working on the fix as we speak.

**Comment by catlook** [comment]
review my edits and see if you agree

**Review by cal27279 — COMMENTED** [review]
Completely agree, thank you!

**Review by viridaria — APPROVED** [review]

**Pull request merged**
